### ISSUE TITLE
title的值 0.020X逸 float报错

### ISSUE THREAD

**Issue by AisukaYuki** [Haruite/u2_scripts#1]
https://github.com/Hastbin/u2_scripts/blob/663a5ecad2c9d4b04607929d1829febe05bff044/give_sugar.py#L115

ERROR    | __main__:get_soup:121 - could not convert string to float: '0.0203 逸'
我给改成了 下面 span ucoin-gold ucoin-silver ucoin-copper的拼接（
`float(info_block.find('span', {'class': 'ucoin-symbol ucoin-gold'}).text + info_block.find('span', {'class': 'ucoin-symbol ucoin-silver'}).text + info_block.find('span', {'class': 'ucoin-symbol ucoin-copper'}).text)`

瞎改的反正能跑就不管了（

**Comment by Hastbin** [comment]
我当时用的是英文界面，没注意到中文界面是这样的
