### ISSUE TITLE
发糖脚本在同一个人连续回帖时，info保存的json会丢失expect_uc报错。

### ISSUE THREAD

**Issue by AisukaYuki** [Haruite/u2_scripts#3]
然后会不断重复刷新帖子，以至于触发限制，报429过多请求单日请求限制😂
![image](https://github.com/Haruite/u2_scripts/assets/17586327/0ef77c68-3303-49c8-96f4-591a81bbdfd9)

![image](https://github.com/Haruite/u2_scripts/assets/17586327/0147985f-d166-4ddd-9861-995d7cb3c1eb)

**Comment by Haruite** [comment]
这个是由于判断重复给一个人发糖的代码有问题，原来的逻辑是，先检查页面，发糖的时候才有expect_uc，但是我在检查重复的时候对还没有发的糖就拿expect_uc作比较，所以造成错误。另外我在脚本出错后加了sleep(300)，这样就应该不会频繁请求。现在u2的日限制不知道是多少，我同时开3个脚本，每个脚本间隔1分钟都没有问题。

**Comment by AisukaYuki** [comment]
算上放魔，签到，媒体库搜索。估计每日请求限制1.5万次。![image](https://github.com/Haruite/u2_scripts/assets/17586327/e45a225b-0f44-417b-b6af-d4f125056ffd)
