### ISSUE TITLE
qb_del.py使用错误参数格式导致的删除功能异常

### ISSUE THREAD

**Issue by Adachi-Git** [Haruite/u2_scripts#4]
**问题描述：**
发生异常: MissingRequiredParameters400Error
exception: no description
  File "C:\Users\Darling\Desktop\U2\qb_del\qb_del.py", line 188, in main
    self.client.torrents_delete(delete_files=True, delete_hashes=delete_hashes)
  File "C:\Users\Darling\Desktop\U2\qb_del\qb_del.py", line 260, in run
    self.main(min_x=x)
  File "C:\Users\Darling\Desktop\U2\qb_del\qb_del.py", line 264, in <module>
    DeleteTorrents().run()
qbittorrentapi.exceptions.MissingRequiredParameters400Error:

**原代码：**

```
self.client.torrents_delete(delete_files=True, delete_hashes=delete_hashes)
```

**尝试修改后的代码：**
```
self.client.torrents_delete(delete_files=True, hashes='|'.join(delete_hashes))
```

**参考：**
[WebUI-API-(qBittorrent-4.1)](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-pieces-hashes)

PS：就这一行没必要Pull了（

**Comment by Haruite** [comment]
我用的是 qbitorrent-api 的三方实现，具体代码在
https://github.com/rmartin16/qbittorrent-api/blob/main/src/qbittorrentapi/torrents.py#L917
会把 hashes 转成合法的形式

**Comment by Adachi-Git** [comment]
> 我用的是 qbitorrent-api 的三方实现，具体代码在 https://github.com/rmartin16/qbittorrent-api/blob/main/src/qbittorrentapi/torrents.py#L917 会把 hashes 转成合法的形式

>     def torrents_delete(
>         self,
>         delete_files: bool | None = False,
>         torrent_hashes: Iterable[str] | None = None,
