### ISSUE TITLE
catch_magic设置DOWNLOAD_NEW = True, 即便新种不是free, 也会下载

### ISSUE THREAD

**Issue by ironstress** [Haruite/u2_scripts#5]
这是bug吗, 还是就这么设定的?

**Comment by ironstress** [comment]
是跟EFFECTIVE_DELAY这个参数有关吗, 我实在是没看懂'如果该魔法是 free 并且生效时间在此之内，就算种子不是 free 也直接下载'是什么意思

**Comment by Haruite** [comment]
算是bug吧，跟EFFECTIVE_DELAY这个参数无关，感谢指出。

**Comment by ironstress** [comment]
> 算是bug吧，跟EFFECTIVE_DELAY这个参数无关，感谢指出。

测试可用了, 顺带能否举例解释一下EFFECTIVE_DELAY参数的作用吗

**Comment by Haruite** [comment]
> > 算是bug吧，跟EFFECTIVE_DELAY这个参数无关，感谢指出。
> 
> 测试可用了, 顺带能否举例解释一下EFFECTIVE_DELAY参数的作用吗

这个参数主要是对一些滞后生效的魔法，即魔法生效的时间在放魔法的时间之后，意思是如果种子当前不是free但是一段时间后变成free也立即加入下载

**Comment by ironstress** [comment]
单位是什么呢, 修改什么值可以让这个功能不起作用

**Comment by Haruite** [comment]
> 单位是什么呢, 修改什么值可以让这个功能不起作用

单位是秒，改成0不起作用
